# Generated by Django 2.2.3 on 2019-07-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
