# Generated by Django 2.2.3 on 2019-07-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0003_auto_20190718_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release',
            field=models.DateTimeField(),
        ),
    ]
