# Generated by Django 2.2.3 on 2019-07-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0006_auto_20190718_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release',
            field=models.DateField(null=True),
        ),
    ]
